export const TRANSACTION_SERVICE = Symbol('TRANSACTION_SERVICE');
export const TRANSACTION_EVENT = Symbol('TRANSACTION_EVENT');
export const TRANSACTION_REPOSITORY = Symbol('TRANSACTION_REPOSITORY');
export const GRAPHQL_TRANSACTION_PRODUCER = Symbol('GRAPHQL_TRANSACTION_PRODUCER');
