export const TRANSACTION_REPOSITORY = Symbol('TRANSACTION_REPOSITORY');
export const TRANSACTION_SERVICE = Symbol('TRANSACTION_SERVICE');
export const TRANSFER_TYPE_SERVICE = Symbol('TRANSFER_TYPE_SERVICE');
export const TRANSFER_TYPE_REPOSITORY = Symbol('TRANSFER_TYPE_REPOSITORY');
export const TRANSACTION_TYPE_SERVICE = Symbol('TRANSACTION_TYPE_SERVICE');
export const TRANSACTION_TYPE_REPOSITORY = Symbol('TRANSACTION_TYPE_REPOSITORY');
export const TRANSACTION_STATUS_SERVICE = Symbol('TRANSACTION_STATUS_SERVICE');
export const TRANSACTION_STATUS_REPOSITORY = Symbol('TRANSACTION_STATUS_REPOSITORY');
