export const TRANSACTION_SERVICE = Symbol('TRANSACTION_SERVICE');
export const TRANSACTION_EVENT = Symbol('TRANSACTION_EVENT');
export const TRANSACTION_MICROSERVICE_PRODUCER = Symbol('TRANSACTION_MICROSERVICE_PRODUCER');
